import Foundation

typealias CopilotACPUpdate = ACPExternalAgentUpdate
typealias CopilotNormalizedEvent = ACPExternalAgentNormalizedEvent
typealias CopilotACPEventNormalizer = ACPExternalAgentEventNormalizer