//
//  ToolCall.swift
//  agentGui
//
//  Created by feint on 2026/2/10.
//

import SwiftData
import Foundation

@Model
final class ToolCall {
    /// 唯一标识符
    var id: UUID

    /// 工具调用 ID (来自 ACP)
    var toolCallId: String

    /// 工具类型
    var kind: ToolKind

    /// 显示标题
    var title: String?

    /// 状态
    var status: ToolStatus

    /// 关联的文件路径
    var filePath: String?

    /// Diff 内容 (用于编辑操作)
    var diffContent: String?

    /// 终端输出
    var terminalOutput: String?

    /// Structured summary for large text results.
    var toolResultSummary: String?

    /// Payload reference when the tool result is stored out-of-band.
    var toolPayloadRef: String?

    /// Raw character count before budget shaping.
    var toolResultRawChars: Int?

    /// Character count injected back into the model context.
    var toolResultInjectedChars: Int?

    /// Total number of times a payload was read through read_tool_payload.
    var toolPayloadReadCount: Int?

    /// Injection mode raw value: inline | preview | referenced.
    var toolResultInjectionMode: String?

    /// Last read range or cursor used when reading a payload.
    var toolPayloadLastReadRange: String?

    /// Unified tool definition ID used to construct this tool schema
    var toolDefinitionID: String?

    /// Unified schema version captured when the tool call was created
    var toolSchemaVersion: Int?

    /// Why this tool was exposed to the model in the current context
    var toolExposureSource: String?

    /// Execution context raw value: mainAgent | subagent | workflowWorker
    var toolExecutionContext: String?

    /// Managed bash task ID
    var terminalTaskId: String?

    /// Managed bash task status raw value
    var terminalTaskStatus: String?

    /// Latest prompt or task summary shown in the UI
    var terminalPromptSummary: String?

    /// JSON payload describing agent actions taken on the terminal task
    var terminalAgentActionsJSON: String?

    /// Managed terminal execution mode raw value
    var terminalExecutionMode: String?

    /// 开始时间
    var startTime: Date?

    /// 结束时间
    var endTime: Date?

    /// 关联的消息
    var message: Message?

    /// 关联的 Agentic Loop 轮次（nil 表示历史数据）
    var agentRound: AgentRound?

    /// 子代理名称（kind == .subagent 时使用）
    var subagentAgentName: String?

    /// 子代理任务描述（kind == .subagent 时使用）
    var subagentTask: String?

    /// AgentMessage 内容类型标签："text" | "structured" | "error"（kind == .subagent 时使用）
    var subagentResultKind: String?

    /// AgentMessage 携带的元数据键值对（轮次数、耗时等）（kind == .subagent 时使用）
    var subagentMessageMetadata: [String: String]?

    /// Unified memory runtime profiles active when this tool call was created
    var memoryRuntimeProfiles: [String]?

    /// Unified memory runtime layers active when this tool call was created
    var memoryRuntimeLayers: [String]?

    /// Unified memory runtime warnings active when this tool call was created
    var memoryRuntimeWarnings: [String]?

    /// Structured runtime snapshot ID captured for this tool call
    var memoryRuntimeSnapshotID: String?

    /// Whether this tool call queued memory work for background consolidation
    var memoryBackgroundConsolidationQueued: Bool?

    /// IDs of records involved in conflict / supersede handling for this tool call
    var memoryConflictRecordIDs: [String]?

    /// IDs of pending confirmation candidates generated by this tool call
    var memoryConfirmationCandidateIDs: [String]?

    /// 子代理的 agentic loop 轮次（kind == .subagent 时使用）
    @Relationship(deleteRule: .cascade, inverse: \AgentRound.subagentToolCall)
    var subagentRounds: [AgentRound] = []

    init(
        toolCallId: String,
        kind: ToolKind,
        message: Message? = nil,
        agentRound: AgentRound? = nil
    ) {
        self.id = UUID()
        self.toolCallId = toolCallId
        self.kind = kind
        self.status = .inProgress
        self.title = nil
        self.filePath = nil
        self.diffContent = nil
        self.terminalOutput = nil
        self.toolResultSummary = nil
        self.toolPayloadRef = nil
        self.toolResultRawChars = nil
        self.toolResultInjectedChars = nil
        self.toolPayloadReadCount = nil
        self.toolResultInjectionMode = nil
        self.toolPayloadLastReadRange = nil
        self.toolDefinitionID = nil
        self.toolSchemaVersion = nil
        self.toolExposureSource = nil
        self.toolExecutionContext = nil
        self.terminalTaskId = nil
        self.terminalTaskStatus = nil
        self.terminalPromptSummary = nil
        self.terminalAgentActionsJSON = nil
        self.terminalExecutionMode = nil
        self.startTime = Date()
        self.endTime = nil
        self.message = message
        self.agentRound = agentRound
        self.memoryRuntimeProfiles = nil
        self.memoryRuntimeLayers = nil
        self.memoryRuntimeWarnings = nil
        self.memoryRuntimeSnapshotID = nil
        self.memoryBackgroundConsolidationQueued = nil
        self.memoryConflictRecordIDs = nil
        self.memoryConfirmationCandidateIDs = nil
    }
}

// MARK: - Computed Properties
extension ToolCall {
    /// 是否进行中
    var isInProgress: Bool {
        status == .inProgress
    }

    /// 是否成功
    var isSuccess: Bool {
        status == .success
    }

    /// 是否失败
    var isFailed: Bool {
        status == .failed
    }

    /// 执行时长（秒）
    var duration: TimeInterval? {
        guard let start = startTime, let end = endTime else { return nil }
        return end.timeIntervalSince(start)
    }

    /// 格式化的状态显示
    var statusDisplay: String {
        return status.displayName
    }

    /// 格式化的文件路径（截短显示）
    var displayPath: String? {
        guard let path = filePath else { return nil }
        let components = path.components(separatedBy: "/")
        if components.count > 3 {
            return ".../" + components.suffix(2).joined(separator: "/")
        }
        return path
    }

    /// 文件名
    var fileName: String? {
        guard let path = filePath else { return nil }
        return (path as NSString).lastPathComponent
    }

    var isVerifierSubagent: Bool {
        kind == .subagent && subagentAgentName == "verifier"
    }

    var verifierPassed: Bool? {
        guard let raw = subagentMessageMetadata?["verificationPassed"]?.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() else {
            return nil
        }
        switch raw {
        case "true":
            return true
        case "false":
            return false
        default:
            return nil
        }
    }

    var verifierSummary: String? {
        guard let summary = subagentMessageMetadata?["verificationSummary"]?.trimmingCharacters(in: .whitespacesAndNewlines),
              !summary.isEmpty else {
            return nil
        }
        return summary
    }

    var verifierVerdictText: String? {
        guard let verifierPassed else { return nil }
        return verifierPassed ? "验证通过" : "验证失败"
    }
}

// MARK: - Factory Methods
extension ToolCall {
    /// 创建文件读取工具调用
    static func readFileCall(toolCallId: String, filePath: String, message: Message) -> ToolCall {
        let toolCall = ToolCall(toolCallId: toolCallId, kind: .read, message: message)
        toolCall.title = "读取文件"
        toolCall.filePath = filePath
        return toolCall
    }

    /// 创建文件编辑工具调用
    static func editFileCall(toolCallId: String, filePath: String, diff: String, message: Message) -> ToolCall {
        let toolCall = ToolCall(toolCallId: toolCallId, kind: .edit, message: message)
        toolCall.title = "编辑文件"
        toolCall.filePath = filePath
        toolCall.diffContent = diff
        return toolCall
    }

    /// 创建终端执行工具调用
    static func terminalCall(toolCallId: String, command: String, message: Message) -> ToolCall {
        let toolCall = ToolCall(toolCallId: toolCallId, kind: .execute, message: message)
        toolCall.title = "执行命令"
        return toolCall
    }

    @MainActor
    static func fixture(
        toolCallId: String = UUID().uuidString,
        kind: ToolKind = .read,
        message: Message? = nil,
        filePath: String? = nil,
        status: ToolStatus = .success
    ) -> ToolCall {
        let toolCall = ToolCall(toolCallId: toolCallId, kind: kind, message: message)
        toolCall.filePath = filePath
        toolCall.status = status
        if status != .inProgress {
            toolCall.endTime = Date()
        }
        return toolCall
    }
}
